const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PROOF_BROWSER_EXECUTABLE});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));
 const [url,out,planning]=process.argv.slice(2),check=name=>{checks.push(name);console.log('PASS '+name);};
 try{
  await page.goto(url+'/#project=alpha&decision=D000001');await page.locator('#token').fill('Synthetic action form test password');await page.locator('#login-submit').click();await page.locator('#detail[data-loaded=true]').waitFor();
  const badges=page.locator('.decision-badges'),dialog=page.locator('#editor'),fields=page.locator('#edit-fields');
  assert.equal(await badges.locator('.badge').first().textContent(),'closed');assert.equal(await badges.getByRole('button',{name:'apply',exact:true}).count(),1);
  const styles=await badges.evaluate(n=>[...n.children].map(e=>{const s=getComputedStyle(e);return {font:s.fontSize,padding:s.padding,border:s.borderRadius,height:e.getBoundingClientRect().height,background:s.backgroundColor};}));assert.deepEqual(styles[0],styles[1]);check('Closed tag and Apply button share translucent size and styling');
  await badges.getByRole('button',{name:'apply',exact:true}).focus();await page.keyboard.press('Enter');await dialog.waitFor();assert.equal(await fields.locator('input:visible,select:visible,textarea:visible').count(),2);assert.equal(await page.locator('#save-edit').textContent(),'Apply');
  const documents=fields.locator('[name=planning_document]'),sections=fields.locator('[name=planning_section]'),picker=fields.locator('.planning-browser');
  await documents.locator('option[value="__add__"]').waitFor({state:'attached'});assert.equal(await sections.isDisabled(),true);assert.equal(await page.locator('#save-edit').isDisabled(),true);assert.equal(await documents.locator('option').filter({hasText:'unsupported.json'}).count(),0);check('Document pool loads supported plans with Section and Apply initially disabled');
  await documents.selectOption('__add__');await picker.getByRole('button',{name:'▸ details',exact:true}).waitFor();assert.equal(await picker.getByRole('button',{name:'Up',exact:true}).isDisabled(),true);await picker.getByRole('button',{name:'▸ details',exact:true}).click();await picker.getByRole('button',{name:'detail.json',exact:true}).waitFor();await picker.getByRole('button',{name:'Up',exact:true}).click();await picker.getByRole('button',{name:'plan.json',exact:true}).waitFor();await picker.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await sections.isDisabled(),true);assert.equal(await page.locator('#save-edit').isDisabled(),true);check('Add document browses nested folders and returns without changing application');
  await documents.selectOption('__add__');await picker.getByLabel('File path',{exact:true}).fill(planning.replace('plan.json','absent.json'));await picker.getByRole('button',{name:'Use path',exact:true}).click();await fields.locator('.error').filter({hasText:'Cannot access this document.'}).waitFor();assert.equal(await badges.locator('.applied-tag').count(),0);assert.equal(await sections.isDisabled(),true);assert.equal(await page.locator('#save-edit').isDisabled(),true);check('Unavailable pasted document reports inline and disables application');
  const choose=async()=>{await documents.selectOption(planning);await sections.locator('option[value=execution]').waitFor({state:'attached'});await sections.selectOption('execution');};
  let release,started,done;const start=new Promise(r=>started=r),finished=new Promise(r=>done=r);await page.route('**/planning-document?*',async route=>{await new Promise(r=>{release=r;started();});await route.continue();done();});await documents.selectOption(planning);await start;await documents.selectOption('');release();await finished;await page.unroute('**/planning-document?*');await page.waitForTimeout(100);assert.equal(await sections.isDisabled(),true);assert.equal(await page.locator('#save-edit').isDisabled(),true);check('Late section response cannot restore a cleared document selection');
  await choose();let v=JSON.parse(fs.readFileSync(planning,'utf8'));v.metadata[0].value='1.1';fs.writeFileSync(planning,JSON.stringify(v));
  await page.locator('#save-edit').click();await page.locator('#form-error').filter({hasText:'Document changed.'}).waitFor();assert.equal(await dialog.isVisible(),true);assert.equal(await documents.inputValue(),planning);await sections.locator('option[value=execution]').waitFor({state:'attached'});await sections.selectOption('execution');check('Document version race retains form and refreshes sections');
  const save=async()=>{const before=await page.locator('#detail .eyebrow').textContent();await page.locator('#save-edit').click();await dialog.waitFor({state:'hidden'});await page.waitForFunction(old=>document.querySelector('#detail .eyebrow')?.textContent!==old,before);await page.locator('#detail[data-loaded=true]').waitFor();};
  await save();await badges.locator('.applied-tag').waitFor();assert.equal(await badges.getByRole('button').count(),0);assert.equal(await badges.locator('.applied-tag').evaluate(n=>n.tabIndex),-1);await page.screenshot({path:out+'/applied-wide.png'});check('Apply becomes a noninteractive soft green applied tag');
  await page.locator('#detail').getByRole('button',{name:'History',exact:true}).click();await page.locator('.application-history').waitFor();assert.ok((await page.locator('.application-history').innerText()).includes('test-plan'));check('Application receipt is visible in historical evidence');
  await page.locator('.closure-slot').getByRole('button',{name:'Reopen',exact:true}).click();await fields.locator('[name=impact]').fill('Reconsider planning');await fields.locator('[name=reason]').fill('Review cycle');await fields.locator('[name=authority_0]').fill('Synthetic owner authorizes reopen');await save();assert.equal(await badges.locator('.badge').count(),1);assert.equal(await badges.textContent(),'open');check('Reopen removes current application and leaves only open tag');
  await page.locator('.closure-slot').getByRole('button',{name:'Decide',exact:true}).click();await fields.locator('[name=answer]').fill('Approved approach');await fields.locator('[name=rationale]').fill('Meets requirements');await save();assert.equal(await badges.getByRole('button',{name:'apply',exact:true}).count(),1);assert.equal(await badges.locator('.applied-tag').count(),0);check('Reclosing the same answer requires a fresh application');
  const fragment=new URLSearchParams({project:'alpha',decision:'D000001','planning-document':planning,'planning-section':'execution'});await page.goto(url+'/#'+fragment);await page.reload();await page.locator('#detail[data-loaded=true]').waitFor();await badges.getByRole('button',{name:'apply',exact:true}).click();await dialog.waitFor();await page.waitForFunction(()=>document.querySelector('[name=planning_section]')?.value==='execution');assert.equal(await fields.locator('[name=planning_document]').inputValue(),planning);await page.locator('#cancel-edit').click();await dialog.waitFor({state:'hidden'});assert.equal(await page.locator('#dirty-dialog').isVisible(),false);assert.equal(await badges.getByRole('button',{name:'apply',exact:true}).evaluate(n=>n===document.activeElement),true);check('Generator-link fields prefill without recording application or creating a dirty cancel prompt');
  await page.setViewportSize({width:320,height:780});await badges.getByRole('button',{name:'apply',exact:true}).click();await dialog.waitFor();await page.waitForFunction(()=>document.querySelector('[name=planning_section]')?.value==='execution');await documents.selectOption('__add__');await picker.getByRole('button',{name:'plan.json',exact:true}).waitFor();assert.ok(await dialog.evaluate(n=>n.scrollWidth<=n.clientWidth+1));await page.screenshot({path:out+'/browse-mobile.png'});await picker.getByRole('button',{name:'▸ details',exact:true}).click();await picker.getByRole('button',{name:'detail.json',exact:true}).click();await sections.locator('option[value=execution]').waitFor({state:'attached'});assert.equal(await page.locator('#save-edit').isDisabled(),true);await sections.selectOption('execution');await page.screenshot({path:out+'/apply-mobile.png'});await save();check('Browse selection and Apply fit a 320-pixel viewport');
  await page.setViewportSize({width:1440,height:1000});await page.locator('#results button[data-key=D000002]').click();await page.locator('#detail[data-loaded=true]').waitFor();await page.locator('#context').getByRole('button',{name:'Deprecate',exact:true}).click();await fields.locator('[name=kind]').selectOption('obsolete');await fields.locator('[name=reason]').fill('Question no longer needed');await fields.locator('[name=authority_0]').fill('Synthetic owner ends question');await save();assert.equal(await badges.textContent(),'deprecated');assert.equal(await badges.getByRole('button').count(),0);check('Deprecated decisions have no Apply control');
  assert.deepEqual(errors,[]);fs.writeFileSync(out+'/observations.json',JSON.stringify({checks,pageerrors:errors},null,2));
 }catch(e){await page.screenshot({path:out+'/failure.png'});fs.writeFileSync(out+'/failure.json',JSON.stringify({error:e.stack,checks,pageerrors:errors},null,2));throw e;}
 finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
