const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PROOF_BROWSER_EXECUTABLE});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));const url=process.argv[2],out=process.argv[3];
 const check=name=>{checks.push(name);console.log('PASS '+name);};
 const create=async(name,id)=>{await page.locator('#new-project').click();await page.locator('#project-fields [name=name]').fill(name);if(id){await page.locator('#project-fields summary').first().click();await page.locator('#project-fields [name=project_id]').fill(id);}await page.locator('#project-save').click();await page.locator('#project-editor').waitFor({state:'hidden'});await page.locator('#maintenance .data-project').filter({hasText:name}).waitFor();};
 try{
  await page.goto(url);await page.locator('#token').waitFor();assert.equal(await page.locator('.topbar').isVisible(),false);assert.equal(await page.locator('.local-sidebar').isVisible(),false);assert.equal(await page.locator('#login-watermark').getAttribute('src'),'/static/watermark.webp');let login=await page.locator('#login-view').boundingBox();assert.ok(Math.abs(login.x+login.width/2-720)<2);assert.ok(Math.abs(login.y+login.height/2-500)<2);await page.screenshot({path:out+'/login-wide.png'});await page.setViewportSize({width:320,height:850});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:out+'/login-narrow.png'});await page.setViewportSize({width:1440,height:1000});check('Sign-in hides shell and centers module with transparent watermark');await page.locator('#token').fill('Synthetic action form test password');await page.locator('#login-submit').click();
  await page.locator('#projects-view').waitFor();assert.equal(await page.locator('#context').isVisible(),false);assert.equal(await page.locator('#admin-watermark').isVisible(),true);assert.equal(await page.locator('#backups-button').isDisabled(),true);assert.equal(await page.locator('link[rel=icon]').getAttribute('href'),'/static/favicon.ico');
  await create('Équipe 12');assert.equal(await page.locator('#project').inputValue(),'equipe-12');assert.ok(page.url().includes('view=projects'));check('Empty state, generated ID and creation stay in administration');
  await page.locator('#decisions-button').click();await page.locator('#context .compact-control button').first().waitFor();assert.equal(await page.locator('#context .compact-control button').count(),8);assert.equal(await page.locator('#context .compact-control button:disabled').count(),8);await page.locator('#projects-button').click();
  await page.locator('#new-project').click();await page.locator('#project-fields [name=name]').fill('Draft project');await page.locator('#project-cancel').click();await page.locator('#project-dirty-keep').click();assert.equal(await page.locator('#project-fields [name=name]').inputValue(),'Draft project');await page.locator('#project-cancel').click();await page.locator('#project-dirty-discard').click();await page.locator('#project-editor').waitFor({state:'hidden'});check('Draft cancellation retains or discards explicitly');
  await page.locator('#decisions-button').click();await page.locator('#new-decision').click();await page.locator('#edit-fields [name=title]').fill('Navigation fixture');await page.locator('#edit-fields [name=question]').fill('Does navigation restore the selected decision?');await page.locator('#save-edit').click();await page.locator('#editor').waitFor({state:'hidden'});await page.locator('#detail[data-loaded=true]').waitFor();
  await page.locator('#projects-button').click();await page.locator('#admin-watermark').waitFor();assert.equal(await page.locator('#context').isVisible(),false);assert.ok(!page.url().includes('decision='));await page.locator('#results button').first().click();await page.locator('#workspace').waitFor();await page.locator('#context .panel-info').waitFor();await page.waitForURL('**/*decision=D000001');check('Results returns to decision and restores controls');
  await page.locator('#projects-button').click();await page.locator('#decisions-button').click();await page.locator('#detail[data-loaded=true]').waitFor();assert.ok(page.url().includes('decision=D000001'));await page.reload();await page.locator('#detail[data-loaded=true]').waitFor();assert.equal(await page.locator('#context .compact-control button:disabled').count()<8,true);
  await page.locator('#projects-button').click();await create('Beta');await page.locator('#project').selectOption('equipe-12');await page.locator('#maintenance .data-project').filter({hasText:'Équipe 12'}).waitFor();assert.equal(await page.locator('#projects-view').isVisible(),true);check('Header project selection preserves administration');
  assert.equal(await page.locator('.page-nav [aria-current=page]').textContent(),'Projects & data');assert.equal(await page.locator('#back-workspace').count(),0);
  await page.locator('#exports-button').click();await page.locator('#file-create').click();await page.locator('#file-create-result').getByText('Created.',{exact:true}).waitFor();await page.locator('#file-list tr[data-artifact]').waitFor();assert.equal(await page.locator('#file-check').isVisible(),false);assert.equal(await page.locator('#file-download').isDisabled(),true);await page.locator('#file-list input[type=radio]').first().check();assert.equal(await page.locator('#file-download').isDisabled(),false);await page.locator('#file-refresh').click();await page.waitForFunction(()=>!document.querySelector('#file-refresh').disabled);assert.equal(await page.locator('#file-download').isDisabled(),true);await page.locator('#file-close').click();
  await page.locator('#backups-button').click();await page.locator('#file-create').click();await page.locator('#file-create-result').getByText('Created.',{exact:true}).waitFor();await page.locator('#file-list input[type=radio]').first().check();await page.locator('#file-check').click();await page.locator('#file-result').getByText('Passed. Active data was not changed.',{exact:true}).waitFor();await page.locator('#file-result details summary').click();assert.equal(await page.locator('#file-manager pre').count(),0);await page.locator('#file-result').getByText('Active data changed',{exact:true}).waitFor();const sizes=await page.locator('#file-download,#file-check').evaluateAll(ns=>ns.map(n=>({w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height})));assert.deepEqual(sizes[0],sizes[1]);assert.equal(await page.locator('.file-datetime span').count(),2);assert.equal(await page.locator('.file-datetime span').last().evaluate(n=>getComputedStyle(n).whiteSpace),'nowrap');await page.screenshot({path:out+'/backup-result.png'});
  await page.locator('#file-rows').selectOption('10');await page.waitForFunction(()=>!document.querySelector('#file-refresh').disabled);assert.equal(await page.locator('#file-download').isDisabled(),true);assert.equal(await page.evaluate(()=>localStorage.getItem('dt.filePageSize')),'10');await page.locator('#file-close').click();await page.locator('#backups-button').click();assert.equal(await page.locator('#file-rows').inputValue(),'10');await page.waitForFunction(()=>!document.querySelector('#file-refresh').disabled);await page.locator('#file-close').click();check('Separate managers, single selection, reset, date/time lines and saved page size');
  await page.locator('#verify-button').click();await page.locator('#data-result').getByText('Passed. Current project data is valid.',{exact:true}).waitFor();assert.equal(await page.locator('#data-result details').count(),1);assert.equal(await page.locator('#maintenance table').count(),0);check('Verify replaces readable result without mixed file table');
  // Exercise real multipage inventory and stale cursors through the shared API.
  await page.evaluate(async()=>{const session=await (await fetch('/api/v1/session')).json(),catalog=await (await fetch('/api/v1/projects')).json(),p=catalog.data.find(p=>p.project_id==='equipe-12');for(let i=0;i<11;i++){const r=await fetch('/api/v1/projects/equipe-12/exports',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data.csrf_token,'X-Ledger-UUID':p.ledger_uuid},body:'{}'});if(!r.ok)throw Error('Fixture export failed');}});
  await page.locator('#exports-button').click();await page.locator('#file-page').filter({hasText:'Page 1 of 2'}).waitFor();assert.equal(await page.locator('#file-list tr[data-artifact]').count(),10);const firstIds=await page.locator('#file-list tr[data-artifact]').evaluateAll(ns=>ns.map(n=>n.dataset.artifact));await page.locator('#file-next').click();await page.locator('#file-page').filter({hasText:'Page 2 of 2'}).waitFor();assert.equal(await page.locator('#file-list tr[data-artifact]').count(),2);await page.locator('#file-prev').click();await page.locator('#file-page').filter({hasText:'Page 1 of 2'}).waitFor();assert.deepEqual(await page.locator('#file-list tr[data-artifact]').evaluateAll(ns=>ns.map(n=>n.dataset.artifact)),firstIds);
  await page.locator('#file-rows').selectOption('100');await page.waitForFunction(()=>!document.querySelector('#file-refresh').disabled);assert.equal(await page.locator('#file-list tr[data-artifact]').count(),12);await page.locator('#file-rows').selectOption('10');await page.waitForFunction(()=>!document.querySelector('#file-refresh').disabled);
  await page.evaluate(async()=>{const session=await (await fetch('/api/v1/session')).json(),catalog=await (await fetch('/api/v1/projects')).json(),p=catalog.data.find(p=>p.project_id==='equipe-12');await fetch('/api/v1/projects/equipe-12/exports',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data.csrf_token,'X-Ledger-UUID':p.ledger_uuid},body:'{}'});});await page.locator('#file-next').click();await page.locator('#file-error').filter({hasText:'Files changed; refresh the list.'}).waitFor();assert.equal(await page.locator('#file-next').isDisabled(),true);await page.locator('#file-refresh').click();await page.waitForFunction(()=>!document.querySelector('#file-refresh').disabled);await page.locator('#file-close').click();check('Real paging replaces rows, counts, previous, 100 size and stale inventory recovery');
  let lost=false;await page.route('**/projects/equipe-12/backups',async route=>{if(!lost){lost=true;await route.fetch();await route.abort();}else await route.continue();});await page.locator('#backups-button').click();await page.waitForFunction(()=>!document.querySelector('#file-refresh').disabled);await page.locator('#file-create').click();await page.locator('#file-create-result').getByText(/Outcome unknown/).waitFor();assert.equal(await page.locator('#file-create').isDisabled(),true);await page.locator('#file-refresh').click();await page.waitForFunction(()=>!document.querySelector('#file-refresh').disabled);assert.equal(await page.locator('#file-create').isDisabled(),true);await page.locator('#file-close').click();await page.unroute('**/projects/equipe-12/backups');check('Unknown creation outcome survives refresh without duplicate submission');
  const visual=await page.locator('#admin-controls .compact-control button').first().evaluate(n=>({fill:getComputedStyle(n).backgroundColor,opacity:getComputedStyle(n).opacity}));assert.equal(visual.opacity,'1');assert.match(visual.fill,/rgba/);await page.screenshot({path:out+'/translucent-controls.png'});
  // Drop both delivery attempts after committed registry requests; retry must replay.
  let dropped=0;await page.route('**/api/v1/projects',async route=>{if(route.request().method()==='POST'&&dropped<2){dropped++;await route.fetch();await route.abort();}else await route.continue();});
  await page.locator('#new-project').click();await page.locator('#project-fields [name=name]').fill('Replay');await page.locator('#project-save').click();await page.locator('#project-recovery').getByRole('button',{name:'Retry original save'}).waitFor();await page.locator('#project-recovery').getByRole('button',{name:'Retry original save'}).click();await page.locator('#project-editor').waitFor({state:'hidden'});await page.unroute('**/api/v1/projects');await page.locator('#project-admin tr[data-project=replay]').waitFor();assert.equal(await page.locator('#project-admin tr[data-project=replay]').count(),1);check('Unknown registry outcome replays exact request');
  await page.locator('#project-admin tr[data-project=beta]').getByRole('button',{name:'Disable',exact:true}).click();await page.locator('#project-confirm-save').click();await page.locator('#project-confirm').waitFor({state:'hidden'});assert.equal(await page.locator('#project').inputValue(),'replay');await page.locator('#project-admin tr[data-project=beta]').getByRole('button',{name:'Beta',exact:true}).click();await page.locator('#maintenance').getByText('This project is disabled. Enable it to access its data.').waitFor();assert.equal(await page.locator('#results button').count(),0);assert.equal(await page.locator('#backups-button').isDisabled(),true);assert.equal(await page.locator('link[rel=icon]').getAttribute('href'),'/static/favicon.ico');await page.locator('#project-admin tr[data-project=beta]').getByRole('button',{name:'Enable',exact:true}).click();await page.locator('#project-confirm-save').click();await page.locator('#project-confirm').waitFor({state:'hidden'});await page.locator('#exports-button').waitFor();check('Row access changes preserve selection; disabled selection clears data');
  await page.locator('#add-existing').click();await page.locator('#project-fields select option').nth(1).waitFor({state:'attached'});assert.equal(await page.locator('#project-fields input[name=relative_path]').count(),0);const choices=await page.locator('#project-fields select option').count();assert.equal(choices,3);await page.locator('#project-fields [name=name]').fill('Imported project');await page.locator('#project-fields select').selectOption({index:1});await page.locator('#project-save').click();await page.locator('#project-editor').waitFor({state:'hidden'});await page.locator('#project-admin tr[data-project=imported-project]').waitFor();check('Prepared candidates populate guided registration without raw paths');
  // Session rejection retains the catalog draft through account reauthentication.
  await page.locator('#new-project').click();await page.locator('#project-fields [name=name]').fill('Reauthenticated');
  let expired=false;await page.route('**/api/v1/projects',async route=>{if(route.request().method()==='POST'&&!expired){expired=true;await route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({ok:false,error:{code:'UNAUTHORIZED',message:'Sign in again.'}})});}else await route.continue();});
  await page.locator('#project-save').click();await page.locator('#project-form-error').filter({hasText:'Sign in again.'}).waitFor();assert.equal(await page.locator('#project-fields [name=name]').inputValue(),'Reauthenticated');await page.locator('#project-signin').click();await page.locator('#current-password').fill('Synthetic action form test password');await page.locator('#account-signin').click();await page.locator('#account-message').filter({hasText:'Signed in.'}).waitFor();await page.locator('#close-account').click();await page.locator('#project-save').click();await page.locator('#project-editor').waitFor({state:'hidden'});await page.locator('#project-admin tr[data-project=reauthenticated]').waitFor();await page.unroute('**/api/v1/projects');check('Catalog draft survives session rejection and reauthentication');
  // A closed manager must discard its delayed response.
  let release,delivered;const gate=new Promise(resolve=>release=resolve),done=new Promise(resolve=>delivered=resolve);
  await page.route('**/projects/equipe-12/artifacts?**',async route=>{const response=await route.fetch();await gate;await route.fulfill({response});delivered();});
  await page.locator('#project').selectOption('equipe-12');await page.locator('#backups-button').click();await page.locator('#file-close').click();await page.locator('#project').selectOption('beta');release();await done;await page.unroute('**/projects/equipe-12/artifacts?**');assert.equal(await page.locator('#file-manager').isVisible(),false);check('Late manager response cannot reopen or cross project scope');
  assert.equal(await page.locator('#projects-view #service-controls').count(),0);await page.locator('#freshness').click();await page.locator('#service-controls').waitFor();await page.locator('#stop-service').click();await page.locator('#stop-service-confirm').waitFor();await page.locator('#cancel-stop-service').click();assert.equal(await page.locator('#stop-service-confirm').isVisible(),false);await page.screenshot({path:out+'/service-popup.png'});await page.locator('#close-live-review').click();check('Service stop is in Workspace updates and remains cancellable');
  // Bounded rendering fixture: 100 public metadata rows, never production data.
  await page.route('**/projects/beta/artifacts?**',async route=>{const response=await route.fetch(),value=await response.json();value.data=Array.from({length:100},(_,i)=>({artifact_id:'layout-'+i,kind:'backup',state:'complete',created_at:'2026-10-05T10:00:00Z',revision:i,size:1,sha256:'synthetic-layout'}));Object.assign(value,{page_index:1,page_count:1,total_count:100,next_cursor:null,previous_cursor:null});await route.fulfill({response,json:value});});
  await page.locator('#backups-button').click();await page.locator('#file-list tr[data-artifact]').nth(99).waitFor({state:'attached'});assert.ok(await page.locator('#file-manager').evaluate(n=>n.getBoundingClientRect().height<=innerHeight*.85+1));assert.ok(await page.locator('#file-next').evaluate(n=>n.getBoundingClientRect().bottom<innerHeight));await page.screenshot({path:out+'/manager-100-rows.png'});await page.setViewportSize({width:320,height:850});assert.ok(await page.locator('#file-manager').evaluate(n=>n.scrollWidth<=n.clientWidth));assert.ok(await page.locator('#file-download').evaluate(n=>n.getBoundingClientRect().bottom<innerHeight));await page.screenshot({path:out+'/manager-narrow.png'});await page.locator('#file-close').click();await page.unroute('**/projects/beta/artifacts?**');await page.setViewportSize({width:1440,height:1000});check('100-row bounded manager and 320px footer remain reachable');
  await page.screenshot({path:out+'/projects-wide.png'});
  await page.setViewportSize({width:320,height:850});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#new-project').click();assert.ok(await page.locator('#project-editor').evaluate(n=>n.scrollWidth<=n.clientWidth));await page.locator('#project-fields [name=name]').fill('Narrow');await page.screenshot({path:out+'/projects-narrow.png'});await page.locator('#project-cancel').click();await page.locator('#project-dirty-discard').click();check('320px page and dialog contain their content');
  if(process.env.PROOF_FULL_BROWSER){const extension=out+'/zoom-extension';fs.mkdirSync(extension,{recursive:true});fs.writeFileSync(extension+'/manifest.json',JSON.stringify({manifest_version:3,name:'Isolated zoom verification',version:'1.0',permissions:['tabs'],background:{service_worker:'worker.js'}}));fs.writeFileSync(extension+'/worker.js','chrome.runtime.onInstalled.addListener(()=>{});');const context=await chromium.launchPersistentContext(out+'/zoom-profile',{headless:true,executablePath:process.env.PROOF_FULL_BROWSER,viewport:null,ignoreDefaultArgs:['--disable-extensions'],args:['--window-size=1440,1000',`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});try{await context.addCookies(await page.context().cookies());const p=await context.newPage();await p.goto(url+'/#project=beta&view=projects');await p.locator('#projects-view').waitFor();const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');assert.equal(await worker.evaluate(async()=>{const tabs=await chrome.tabs.query({});const tab=tabs.find(t=>t.url.startsWith('http://127.0.0.1'));await chrome.tabs.setZoom(tab.id,2);return chrome.tabs.getZoom(tab.id);}),2);await p.locator('#new-project').click();assert.ok(await p.locator('#project-editor').evaluate(n=>n.scrollWidth<=n.clientWidth));await p.screenshot({path:out+'/projects-200-percent.png'});await p.locator('#project-cancel').click();await p.locator('#backups-button').click();await p.waitForFunction(()=>!document.querySelector('#file-refresh').disabled);assert.ok(await p.locator('#file-manager').evaluate(n=>n.scrollWidth<=n.clientWidth));assert.ok(await p.locator('#file-download').evaluate(n=>n.getBoundingClientRect().bottom<innerHeight));const zoomGeometry=await p.evaluate(()=>({innerWidth,innerHeight,visualWidth:visualViewport.width,visualHeight:visualViewport.height,dialog:document.querySelector('#file-manager').getBoundingClientRect().toJSON()}));fs.writeFileSync(out+'/zoom-geometry.json',JSON.stringify(zoomGeometry,null,2));assert.ok(zoomGeometry.dialog.y>=0&&zoomGeometry.dialog.bottom<=zoomGeometry.visualHeight);await p.bringToFront();await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const capture=await p.context().newCDPSession(p);const pixels=await capture.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:true});fs.writeFileSync(out+'/manager-200-percent.png',Buffer.from(pixels.data,'base64'));await capture.detach();check('Actual 200 percent browser zoom');}finally{await context.close();}}
  assert.deepEqual(errors,[]);fs.writeFileSync(out+'/observations.json',JSON.stringify({checks,errors},null,2));
 }catch(e){await page.screenshot({path:out+'/failure.png'});throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
