const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PROOF_BROWSER_EXECUTABLE});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));const url=process.argv[2],out=process.argv[3];
 const check=name=>{checks.push(name);console.log('PASS '+name);};
 const create=async(name,id)=>{await page.locator('#new-project').click();await page.locator('#project-fields [name=name]').fill(name);if(id){await page.locator('#project-fields summary').first().click();await page.locator('#project-fields [name=project_id]').fill(id);}await page.locator('#project-save').click();await page.locator('#project-editor').waitFor({state:'hidden'});await page.locator('#maintenance .data-project').filter({hasText:name}).waitFor();};
 try{
  await page.goto(url);await page.locator('#token').fill('Synthetic action form test password');await page.locator('#login-submit').click();
  await page.locator('#projects-view').waitFor();assert.equal(await page.locator('#context').isVisible(),false);assert.equal(await page.locator('#admin-watermark').isVisible(),true);assert.equal(await page.locator('#back-workspace').isDisabled(),true);
  await create('Équipe 12');assert.equal(await page.locator('#project').inputValue(),'equipe-12');assert.ok(page.url().includes('view=projects'));check('Empty state, generated ID and creation stay in administration');
  await page.locator('#new-project').click();await page.locator('#project-fields [name=name]').fill('Draft project');await page.locator('#project-cancel').click();await page.locator('#project-dirty-keep').click();assert.equal(await page.locator('#project-fields [name=name]').inputValue(),'Draft project');await page.locator('#project-cancel').click();await page.locator('#project-dirty-discard').click();await page.locator('#project-editor').waitFor({state:'hidden'});check('Draft cancellation retains or discards explicitly');
  await page.locator('#back-workspace').click();await page.locator('#new-decision').click();await page.locator('#edit-fields [name=title]').fill('Navigation fixture');await page.locator('#edit-fields [name=question]').fill('Does navigation restore the selected decision?');await page.locator('#save-edit').click();await page.locator('#editor').waitFor({state:'hidden'});await page.locator('#detail[data-loaded=true]').waitFor();
  await page.locator('#projects-button').click();await page.locator('#admin-watermark').waitFor();assert.equal(await page.locator('#context').isVisible(),false);assert.ok(!page.url().includes('decision='));await page.locator('#results button').first().click();await page.locator('#workspace').waitFor();await page.locator('#context .panel-info').waitFor();await page.waitForURL('**/*decision=D000001');check('Results returns to decision and restores controls');
  await page.locator('#projects-button').click();await create('Beta');await page.locator('#project').selectOption('equipe-12');await page.locator('#maintenance .data-project').filter({hasText:'Équipe 12'}).waitFor();assert.equal(await page.locator('#projects-view').isVisible(),true);check('Header project selection preserves administration');
  await page.locator('#maintenance').getByRole('button',{name:'Export',exact:true}).click();await page.locator('#maintenance').getByText('Export complete · Équipe 12',{exact:true}).waitFor();await page.locator('#maintenance tr[data-artifact]').waitFor();
  await page.locator('#maintenance').getByRole('button',{name:'Refresh',exact:true}).click();await page.locator('#maintenance').getByRole('button',{name:'Refresh',exact:true}).click();assert.equal(await page.locator('#maintenance tr[data-artifact]').count(),1);
  await page.locator('#maintenance').getByRole('button',{name:'Backup',exact:true}).click();await page.locator('#maintenance').getByRole('button',{name:'Check backup',exact:true}).waitFor();await page.locator('#maintenance').getByRole('button',{name:'Check backup',exact:true}).click();await page.locator('#maintenance').getByText('Backup check complete · Équipe 12',{exact:true}).waitFor();await page.locator('#maintenance').getByRole('button',{name:'Verify',exact:true}).click();await page.locator('#maintenance').getByText('Verify complete · Équipe 12',{exact:true}).waitFor();assert.equal(await page.locator('#maintenance details').count(),1);check('Data operations replace summary and refresh files without duplicates');
  // Drop both delivery attempts after committed registry requests; retry must replay.
  let dropped=0;await page.route('**/api/v1/projects',async route=>{if(route.request().method()==='POST'&&dropped<2){dropped++;await route.fetch();await route.abort();}else await route.continue();});
  await page.locator('#new-project').click();await page.locator('#project-fields [name=name]').fill('Replay');await page.locator('#project-save').click();await page.locator('#project-recovery').getByRole('button',{name:'Retry original save'}).waitFor();await page.locator('#project-recovery').getByRole('button',{name:'Retry original save'}).click();await page.locator('#project-editor').waitFor({state:'hidden'});await page.unroute('**/api/v1/projects');await page.locator('#project-admin tr[data-project=replay]').waitFor();assert.equal(await page.locator('#project-admin tr[data-project=replay]').count(),1);check('Unknown registry outcome replays exact request');
  await page.locator('#project-admin tr[data-project=beta]').getByRole('button',{name:'Disable',exact:true}).click();await page.locator('#project-confirm-save').click();await page.locator('#project-confirm').waitFor({state:'hidden'});assert.equal(await page.locator('#project').inputValue(),'replay');await page.locator('#project-admin tr[data-project=beta]').getByRole('button',{name:'Beta',exact:true}).click();await page.locator('#maintenance').getByText('This project is disabled. Enable it to access its data.').waitFor();assert.equal(await page.locator('#results button').count(),0);assert.equal(await page.locator('#back-workspace').isDisabled(),true);await page.locator('#project-admin tr[data-project=beta]').getByRole('button',{name:'Enable',exact:true}).click();await page.locator('#project-confirm-save').click();await page.locator('#project-confirm').waitFor({state:'hidden'});await page.locator('#maintenance').getByRole('button',{name:'Export',exact:true}).waitFor();check('Row access changes preserve selection; disabled selection clears data');
  await page.locator('#add-existing').click();await page.locator('#project-fields select option').nth(1).waitFor({state:'attached'});assert.equal(await page.locator('#project-fields input[name=relative_path]').count(),0);const choices=await page.locator('#project-fields select option').count();assert.equal(choices,3);await page.locator('#project-fields [name=name]').fill('Imported project');await page.locator('#project-fields select').selectOption({index:1});await page.locator('#project-save').click();await page.locator('#project-editor').waitFor({state:'hidden'});await page.locator('#project-admin tr[data-project=imported-project]').waitFor();check('Prepared candidates populate guided registration without raw paths');
  // Session rejection retains the catalog draft through account reauthentication.
  await page.locator('#new-project').click();await page.locator('#project-fields [name=name]').fill('Reauthenticated');
  let expired=false;await page.route('**/api/v1/projects',async route=>{if(route.request().method()==='POST'&&!expired){expired=true;await route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({ok:false,error:{code:'UNAUTHORIZED',message:'Sign in again.'}})});}else await route.continue();});
  await page.locator('#project-save').click();await page.locator('#project-form-error').filter({hasText:'Sign in again.'}).waitFor();assert.equal(await page.locator('#project-fields [name=name]').inputValue(),'Reauthenticated');await page.locator('#project-signin').click();await page.locator('#current-password').fill('Synthetic action form test password');await page.locator('#account-signin').click();await page.locator('#account-message').filter({hasText:'Signed in.'}).waitFor();await page.locator('#close-account').click();await page.locator('#project-save').click();await page.locator('#project-editor').waitFor({state:'hidden'});await page.locator('#project-admin tr[data-project=reauthenticated]').waitFor();await page.unroute('**/api/v1/projects');check('Catalog draft survives session rejection and reauthentication');
  // A slow prior project's file response cannot repaint the new selection.
  let held=false,release,delivered;const gate=new Promise(resolve=>release=resolve),done=new Promise(resolve=>delivered=resolve);
  await page.route('**/projects/equipe-12/artifacts',async route=>{held=true;const response=await route.fetch();await gate;await route.fulfill({response});delivered();});
  await page.locator('#project').selectOption('equipe-12');await page.waitForFunction(()=>document.querySelector('#maintenance .data-project')?.textContent==='Équipe 12');
  await page.locator('#project').selectOption('beta');await page.locator('#maintenance .data-project').filter({hasText:'Beta'}).waitFor();release();await done;await page.unroute('**/projects/equipe-12/artifacts');assert.equal(await page.locator('#maintenance tr[data-artifact]').count(),0);check('Late file response cannot cross project scope');
  await page.locator('#stop-service').click();await page.locator('#stop-service-confirm').waitFor();await page.locator('#cancel-stop-service').click();assert.equal(await page.locator('#stop-service-confirm').isVisible(),false);check('Service stop remains separate and cancellable');
  await page.screenshot({path:out+'/projects-wide.png'});
  await page.setViewportSize({width:320,height:850});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#new-project').click();assert.ok(await page.locator('#project-editor').evaluate(n=>n.scrollWidth<=n.clientWidth));await page.locator('#project-fields [name=name]').fill('Narrow');await page.screenshot({path:out+'/projects-narrow.png'});await page.locator('#project-cancel').click();await page.locator('#project-dirty-discard').click();check('320px page and dialog contain their content');
  if(process.env.PROOF_FULL_BROWSER){const extension=out+'/zoom-extension';fs.mkdirSync(extension,{recursive:true});fs.writeFileSync(extension+'/manifest.json',JSON.stringify({manifest_version:3,name:'Isolated zoom verification',version:'1.0',permissions:['tabs'],background:{service_worker:'worker.js'}}));fs.writeFileSync(extension+'/worker.js','chrome.runtime.onInstalled.addListener(()=>{});');const context=await chromium.launchPersistentContext(out+'/zoom-profile',{headless:true,executablePath:process.env.PROOF_FULL_BROWSER,viewport:{width:1440,height:1000},ignoreDefaultArgs:['--disable-extensions'],args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});try{await context.addCookies(await page.context().cookies());const p=await context.newPage();await p.goto(url+'/#project=beta&view=projects');await p.locator('#projects-view').waitFor();const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');assert.equal(await worker.evaluate(async()=>{const tabs=await chrome.tabs.query({});const tab=tabs.find(t=>t.url.startsWith('http://127.0.0.1'));await chrome.tabs.setZoom(tab.id,2);return chrome.tabs.getZoom(tab.id);}),2);await p.locator('#new-project').click();assert.ok(await p.locator('#project-editor').evaluate(n=>n.scrollWidth<=n.clientWidth));await p.screenshot({path:out+'/projects-200-percent.png'});check('Actual 200 percent browser zoom');}finally{await context.close();}}
  assert.deepEqual(errors,[]);fs.writeFileSync(out+'/observations.json',JSON.stringify({checks,errors},null,2));
 }catch(e){await page.screenshot({path:out+'/failure.png'});throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
