const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PROOF_BROWSER_EXECUTABLE});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),checks=[],errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const check=name=>{checks.push(name);console.log('PASS '+name);};
 const out=process.argv[3];
 try{
  await page.goto(process.argv[2]);await page.locator('#token').fill('Synthetic action form test password');await page.locator('#login-submit').click();
  await page.locator('#new-project').click();await page.locator('#project-fields input[name=name]').fill('Refresh review');await page.locator('#project-fields details').first().locator('summary').click();await page.locator('#project-fields input[name=project_id]').fill('review');await page.locator('#project-save').click();await page.locator('#project-editor').waitFor({state:'hidden'});await page.locator('#decisions-button').click();
  // A second participant writes through the same authenticated API with explicit binding.
  const mutate=async(operations,keys=[])=>page.evaluate(async({operations,keys})=>{
   const session=await (await fetch('/api/v1/session')).json(),catalog=await (await fetch('/api/v1/projects')).json();const project=catalog.data.find(p=>p.project_id==='review');const base='/api/v1/projects/review';const headers={'X-Ledger-UUID':project.ledger_uuid};
   const list=await (await fetch(base+'/decisions',{headers})).json(),revisions={};for(const key of keys)revisions[key]=(await (await fetch(base+'/decisions/'+key,{headers})).json()).data.revision;
   const response=await fetch(base+'/changes',{method:'POST',headers:{...headers,'Content-Type':'application/json','X-CSRF-Token':session.data.csrf_token},body:JSON.stringify({expected_ledger_uuid:project.ledger_uuid,expected_revision:list.revision,expected_decision_revisions:revisions,request_id:crypto.randomUUID(),reason:'Synthetic remote refresh participant',authority_refs:['Synthetic fixture approval'],operations})});const result=await response.json();if(!result.ok)throw Error(JSON.stringify(result));return result;
  },{operations,keys});
  await mutate([{op:'decision.create',data:{title:'Original title',question:'What should refresh do?'}},{op:'decision.create',data:{title:'Neighbor',question:'Related context?'}}]);
  await page.reload();await page.locator('#detail[data-loaded=true]').waitFor();
  const green=()=>page.waitForFunction(()=>document.querySelector('#freshness').classList.contains('green'));
  const red=()=>page.waitForFunction(()=>document.querySelector('#freshness').classList.contains('red'));
  await green();check('default selection binds selected-key stream without false red');
  await mutate([{op:'decision.edit',key:'D000001',data:{title:'Remote title'}}],['D000001']);await red();
  await page.locator('#freshness').click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#live-review').waitFor({state:'hidden'});await green();assert.equal(await page.locator('#detail h2').textContent(),'Remote title');check('normal refresh replaces selected detail and results, then turns green');
  await mutate([{op:'link.add',key:'D000001',data:{target_key:'D000002',type:'relates_to'}}],['D000001','D000002']);await red();await page.locator('#freshness').click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#live-review').waitFor({state:'hidden'});await green();
  await mutate([{op:'decision.edit',key:'D000002',data:{title:'Neighbor updated'}}],['D000002']);await page.waitForFunction(()=>document.querySelector('#freshness').classList.contains('yellow'));await page.locator('#freshness').click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#live-review').waitFor({state:'hidden'});await green();check('neighbor context refresh resolves yellow');
  await page.locator('#context').getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#edit-fields [name=title]').fill('Unsaved draft');
  await mutate([{op:'decision.edit',key:'D000001',data:{title:'Second remote title'}}],['D000001']);await red();
  await page.locator('#edit-form').getByRole('button',{name:'Review workspace updates',exact:true}).click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('.revision-comparison').waitFor();
  assert.equal(await page.locator('#edit-fields [name=title]').inputValue(),'Unsaved draft');assert.equal(await page.locator('#detail h2').textContent(),'Remote title');await red();
  assert(await page.locator('#editor').evaluate(e=>e.matches(':modal')));await page.screenshot({path:out+'/modal-comparison.png'});check('editor-local refresh compares without changing draft or saved baseline');
  await page.locator('#live-review').getByRole('button',{name:'Rebase draft for review',exact:true}).click();await page.locator('#live-review').waitFor({state:'hidden'});assert.equal(await page.locator('#edit-fields [name=title]').inputValue(),'Unsaved draft');assert.equal(await page.locator('#detail h2').textContent(),'Second remote title');await green();
  const saved=await page.evaluate(async()=>{const c=await (await fetch('/api/v1/projects')).json();return (await (await fetch('/api/v1/projects/review/decisions/D000001',{headers:{'X-Ledger-UUID':c.data[0].ledger_uuid}})).json()).data.title;});assert.equal(saved,'Second remote title');check('explicit rebase retains text, installs reviewed baseline and sends no save');
  await page.locator('#cancel-edit').click();await page.locator('#dirty-discard').click();
  await page.locator('#freshness').click();await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide')));await page.locator('#live-review').getByRole('button',{name:'Retry connection',exact:true}).waitFor();await page.locator('#live-review').getByRole('button',{name:'Retry connection',exact:true}).click();await page.locator('#live-review').waitFor({state:'hidden'});await green();check('connection loss inside popup exposes working retry without reload');
  await page.evaluate(()=>{window.dispatchEvent(new PageTransitionEvent('pagehide'));window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await green();assert.equal(await page.locator('#detail h2').textContent(),'Second remote title');check('persisted page restoration resumes selected monitor without replacing data');
  // A commit during collection must exhaust the bounded retry without partial display replacement.
  await mutate([{op:'decision.edit',key:'D000001',data:{title:'Concurrent saved title'}}],['D000001']);await red();let attempts=0;
  await page.route('**/decisions/D000001/context',async route=>{attempts++;const response=await route.fetch();const body=await response.json();body.revision++;await route.fulfill({response,json:body});});
  await page.locator('#freshness').click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#live-review-content .error').waitFor();assert.equal(attempts,2);assert.equal(await page.locator('#detail h2').textContent(),'Second remote title');await red();check('concurrent collection fails after two attempts and preserves coherent display');
  await page.unroute('**/decisions/D000001/context');await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#live-review').waitFor({state:'hidden'});await green();
  // A delayed response after navigation cannot paint the previous workspace.
  await page.route('**/decisions/D000001/context',async route=>{await new Promise(r=>setTimeout(r,500));try{await route.continue();}catch{}});
  await page.locator('#freshness').click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#close-live-review').click();await page.locator('#projects-button').click();await page.locator('#projects-view').waitFor();await page.waitForTimeout(650);assert(await page.locator('#workspace').isHidden());check('late refresh after navigation is cancelled');await page.unroute('**/decisions/D000001/context');await page.locator('#decisions-button').click();await page.locator('#detail[data-loaded=true]').waitFor();await green();
  // Remote closure makes an ordinary edit rebase illegal, while its text remains available.
  await page.locator('#context').getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#edit-fields [name=title]').fill('Retained on remote close');
  await mutate([{op:'decision.close',key:'D000001',data:{answer:'Synthetic approved answer',rationale:'Exercise remote closure guard'}}],['D000001']);await red();await page.locator('#edit-form').getByRole('button',{name:'Review workspace updates',exact:true}).click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('.revision-comparison').waitFor();assert.equal(await page.locator('#live-review').getByRole('button',{name:'Rebase draft for review',exact:true}).count(),0);await page.locator('#live-review-content').getByText('Your draft is preserved. Use the existing Reopen or Amend workflow for the current record.',{exact:true}).waitFor();assert.equal(await page.locator('#edit-fields [name=title]').inputValue(),'Retained on remote close');check('remote closure rejects rebase without losing draft');await page.locator('#close-live-review').click();await page.locator('#cancel-edit').click();await page.locator('#dirty-discard').click();
  await mutate([{op:'decision.reopen',key:'D000001',data:{impact:'Synthetic continuation after guard check'}}],['D000001']);await page.locator('#freshness').click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#live-review').waitFor({state:'hidden'});await green();
  // The server commits but the browser loses its response. Rebase must not erase exact-request recovery.
  await page.locator('#context').getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#edit-fields [name=title]').fill('Lost response saved title');
  let releaseSave,commitSeen;const heldSave=new Promise(resolve=>releaseSave=resolve),committed=new Promise(resolve=>commitSeen=resolve);
  await page.route('**/projects/review/changes',async route=>{await route.fetch();commitSeen();await heldSave;await route.abort('failed');});await page.locator('#save-edit').click();await committed;
  await page.locator('#edit-form').getByRole('button',{name:'Review workspace updates',exact:true}).click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('.revision-comparison').waitFor();await page.locator('#live-review').getByRole('button',{name:'Rebase draft for review',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#error').textContent.includes('Retry original save'));assert(await page.locator('#save-edit').isDisabled());check('in-flight save blocks rebase and preserves retained request');await page.locator('#close-live-review').click();releaseSave();await page.locator('#conflict').getByRole('button',{name:'Retry original save',exact:true}).waitFor();
  await page.locator('#edit-form').getByRole('button',{name:'Review workspace updates',exact:true}).click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('.revision-comparison').waitFor();await page.locator('#live-review').getByRole('button',{name:'Rebase draft for review',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#error').textContent.includes('Retry original save'));assert.equal(await page.locator('#edit-fields [name=title]').inputValue(),'Lost response saved title');check('uncertain committed save blocks rebase and retains exact replay');await page.locator('#close-live-review').click();await page.unroute('**/projects/review/changes');await page.locator('#conflict').getByRole('button',{name:'Retry original save',exact:true}).click();await page.locator('#editor').waitFor({state:'hidden'});await green();assert.equal(await page.locator('#detail h2').textContent(),'Lost response saved title');check('original save replay reconciles without duplicate mutation');
  // An authenticated read failure exposes sign-in while retaining the displayed data.
  await page.route('**/projects/review/decisions?*',route=>route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({ok:false,error:{code:'UNAUTHORIZED',message:'Synthetic session expired'}})}));await page.locator('#freshness').click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#live-review').getByRole('button',{name:'Sign in again',exact:true}).waitFor();assert.equal(await page.locator('#detail h2').textContent(),'Lost response saved title');check('session expiry preserves data and offers explicit sign-in');await page.unroute('**/projects/review/decisions?*');await page.locator('#live-review').getByRole('button',{name:'Sign in again',exact:true}).click();await page.locator('#live-review input[type=password]').fill('Synthetic action form test password');await page.locator('#live-review form').getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('#live-review').waitFor({state:'hidden'});await green();check('sign-in recovery reconciles without browser reload');
  // Wrong ledger identity is terminal and cannot be accepted as a refresh.
  await page.route('**/projects/review/decisions?*',async route=>{const response=await route.fetch();const body=await response.json();body.ledger_uuid='wrong-uuid';await route.fulfill({response,json:body});});await page.locator('#freshness').click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#freshness').getAttribute('aria-label')==='Unavailable');assert.equal(await page.locator('#detail h2').textContent(),'Lost response saved title');assert.equal(await page.locator('#live-review').getByRole('button',{name:'Retry connection',exact:true}).count(),0);check('wrong response identity preserves data and remains unavailable');await page.unroute('**/projects/review/decisions?*');await page.locator('#close-live-review').click();await page.locator('#project').selectOption('');await page.locator('#project').selectOption('review');await page.locator('#decisions-button').click();await page.locator('#detail[data-loaded=true]').waitFor();await green();
  // A stalled fetch is aborted at the specified manual-refresh deadline, with controls disabled while active.
  await page.route('**/decisions/D000001/context',async route=>{await new Promise(r=>setTimeout(r,21000));try{await route.continue();}catch{}});await page.locator('#freshness').click();const began=Date.now();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();assert(await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).isDisabled());await page.locator('#live-review-content .error').waitFor({timeout:25000});assert(Date.now()-began<24000);assert.equal(await page.locator('#detail h2').textContent(),'Lost response saved title');check('manual refresh deadline aborts stalled collection and disables repeat clicks');await page.unroute('**/decisions/D000001/context');await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#live-review').waitFor({state:'hidden'});await green();
  await page.locator('#projects-button').click();await page.locator('#freshness').click();await page.locator('#live-review').getByRole('button',{name:'Refresh results',exact:true}).click();await page.locator('#live-review-content').getByText('Projects & data catalog refreshed.',{exact:true}).waitFor();assert(await page.locator('#projects-view').isVisible());check('Projects & data refresh stays in catalog view');await page.locator('#close-live-review').click();await page.locator('#decisions-button').click();await page.locator('#detail[data-loaded=true]').waitFor();await green();
  assert.deepEqual(errors,[]);await page.screenshot({path:out+'/refreshed-workspace.png'});
 }finally{const visible=await page.evaluate(()=>({freshness:document.querySelector('#freshness')?.outerHTML,error:document.querySelector('#error')?.textContent,detail:document.querySelector('#detail')?.innerText,popup:document.querySelector('#live-review-content')?.innerText}));await page.screenshot({path:out+'/final-state.png'});fs.writeFileSync(out+'/observations.json',JSON.stringify({checks,errors,visible},null,2));await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
