const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PROOF_BROWSER_EXECUTABLE});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
 const origin=process.argv[2],out=process.argv[3];page.on('pageerror',e=>errors.push(e.message));
 const check=s=>checks.push(s);
 try{
  await page.goto(origin);await page.locator('#token').fill('Synthetic action form test password');await page.locator('#login-submit').click();await page.locator('#projects-view').waitFor();
  await page.locator('#saved-button').click();await page.locator('#library-view').waitFor();assert.equal(await page.locator('dialog#saved-admin').count(),0);assert.equal(await page.locator('.page-nav [aria-current=page]').textContent(),'Library');await page.locator('#saved-list').getByText('No saved decisions yet.').waitFor();assert.equal(await page.locator('#project option').count(),1);check('Blank first boot needs no pre-existing project');
  async function editSaved(title){await page.locator('#saved-list .saved-row').filter({hasText:title}).getByRole('button',{name:'View',exact:true}).click();await page.locator('#saved-preview').getByRole('button',{name:'Edit',exact:true}).click();}
  async function saved(title,waitForList=true){await page.locator('#saved-new').click();await page.locator('#saved-title').fill(title);await page.locator('#saved-question').fill('How should this work?');await page.locator('#saved-fields details > summary').click();await page.locator('#saved-answer').fill('Operator-chosen content');await page.locator('#saved-rationale').fill('Synthetic operator rationale for this requirement.');await page.locator('#saved-save').click();await page.locator('#saved-editor').waitFor({state:'hidden'});if(waitForList)await page.locator('#saved-list').getByText(title,{exact:true}).waitFor();}
  await saved('Reusable launch');await saved('Other decision');
  // A committed saved change followed by a failed read must not become an uncertain write.
  let reads=0;await page.route('**/api/v1/saved-decisions?**',async route=>{if(reads++===0)await route.abort();else await route.continue();});
  await saved('Refresh recovery',false);await page.locator('#saved-error').filter({hasText:'saved change committed'}).waitFor();assert.equal(await page.locator('#saved-recovery button').count(),0);await page.locator('#saved-refresh').click();await page.locator('#saved-list').getByText('Refresh recovery',{exact:true}).waitFor();await page.unroute('**/api/v1/saved-decisions?**');check('Acknowledged saved write remains committed when its refresh fails');
  await editSaved('Reusable launch');await page.locator('#saved-fields details > summary').click();await page.locator('#saved-answer').fill('My reviewed answer');
  await page.evaluate(async()=>{const session=await (await fetch('/api/v1/session')).json();const list=await (await fetch('/api/v1/saved-decisions')).json();const row=list.data.find(x=>x.title==='Reusable launch');const item=await (await fetch('/api/v1/saved-decisions/'+row.id)).json();const response=await fetch('/api/v1/saved-decisions/changes',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data.csrf_token},body:JSON.stringify({action:'save',id:row.id,content:{...item.data.content,answer:'Concurrent saved answer'},expected_revision:list.revision,request_id:crypto.randomUUID(),reason:'Synthetic concurrent library edit'})});if(!response.ok)throw Error('Concurrency fixture failed');});
  await page.locator('#saved-save').click();await page.locator('#saved-form-error').filter({hasText:'Saved decisions changed'}).waitFor();assert.equal(await page.locator('#saved-answer').inputValue(),'My reviewed answer');await page.locator('#saved-form-recovery').getByRole('button',{name:'Review current saved items'}).click();await page.locator('#saved-form-recovery').getByText('Concurrent saved answer',{exact:true}).waitFor();await page.locator('#saved-form-recovery').getByRole('button',{name:'Use this revision; keep my draft'}).click();await page.locator('#saved-save').click();await page.locator('#saved-editor').waitFor({state:'hidden'});check('Concurrent saved edit preserves the draft until explicit review and resave');
  await page.locator('#saved-manage-groups').click();await page.locator('#saved-group-name').fill('Websites');await page.locator('#saved-group-form button[type=submit]').click();await page.locator('#saved-group-list').getByText('Websites',{exact:true}).waitFor();await page.locator('#saved-group-close').click();
  const first=page.locator('#saved-list .saved-row').filter({hasText:'Reusable launch'});await editSaved('Reusable launch');await page.locator('#saved-extras > summary').click();await page.locator('#saved-tags select').selectOption({label:'Websites'});await page.locator('#saved-option-add').click();await page.locator('#saved-attachments [name=title]').fill('Local launch proposal');await page.locator('#saved-reference-add').click();await page.locator('#saved-attachments [name=label]').fill('Launch reference');await page.locator('#saved-attachments [name=locator]').fill('https://example.com/launch');await page.locator('#saved-save').click();await page.locator('#saved-editor').waitFor({state:'hidden'});
  await page.locator('#saved-group-filter').selectOption({label:'Websites'});assert.equal(await page.locator('#saved-list .saved-row').count(),1);await page.locator('#saved-check-all').check();await page.locator('#saved-group-filter').selectOption('');assert.equal(await first.locator('input').isChecked(),true);assert.equal(await page.locator('#saved-list button').count(),3);await page.locator('#saved-search').fill('Other decision');await page.locator('#saved-check-all').check();assert.equal(await page.locator('#saved-selection-count').textContent(),'2 selected · 1 shown');await page.locator('#saved-check-all').uncheck();assert.equal(await page.locator('#saved-selection-count').textContent(),'1 selected · 1 shown');await page.locator('#saved-add').click();await page.locator('#saved-staging .saved-row').waitFor();assert.equal(await page.locator('#saved-staging .saved-row').count(),1);await page.locator('#saved-search').fill('');check('Group dropdown, Check all and hidden session selections stage the complete checked set');
  await first.locator('input').uncheck();await page.locator('#saved-list .saved-row').filter({hasText:'Other decision'}).locator('input').check();await page.locator('#saved-add').click();await page.waitForFunction(()=>document.querySelectorAll('#saved-staging .saved-row').length===2);await page.locator('#saved-staging .saved-row').filter({hasText:'Other decision'}).getByRole('button',{name:'Drop'}).click();assert.equal(await page.locator('#saved-staging .saved-row').count(),1);check('Individual addition and drop leave saved originals intact');
  await page.screenshot({path:out+'/library-wide.png'});
  await page.locator('#projects-button').click();assert.equal(await page.locator('.page-nav [aria-current=page]').textContent(),'Projects');await page.locator('#saved-button').click();await page.locator('#library-view').waitFor();assert.equal(await page.locator('#saved-staging .saved-row').count(),1);
  await page.goBack();await page.locator('#projects-view').waitFor();await page.goForward();await page.locator('#library-view').waitFor();assert.equal(await page.locator('#saved-staging .saved-row').count(),1);check('Page switching and Back/Forward preserve staging without a selected project');
  await page.locator('#saved-search').fill('Other decision');assert.equal(await page.locator('#saved-list .saved-row').count(),1);await page.locator('#saved-search').fill('');
  await page.locator('#saved-new').click();await page.locator('#saved-title').fill('Discarded draft');await page.locator('#saved-cancel').click();await page.locator('#saved-dirty-cancel').click();assert.equal(await page.locator('#saved-title').inputValue(),'Discarded draft');await page.locator('#saved-cancel').click();await page.locator('#saved-dirty-discard').click();assert.equal(await page.locator('#saved-editor').isVisible(),false);assert.equal(await page.locator('#saved-staging .saved-row').count(),1);check('Familiar action popup keeps or discards a draft without dropping staging');
  await editSaved('Reusable launch');await page.locator('#saved-extras > summary').click();assert.equal(await page.locator('#saved-attachments [name=title]').inputValue(),'Local launch proposal');assert.equal(await page.locator('#saved-attachments [name=locator]').inputValue(),'https://example.com/launch');await page.locator('#saved-title').fill('Reusable launch');await page.locator('#saved-save').click();await page.locator('#saved-editor').waitFor({state:'hidden'});check('Shared editing preserves proposals, references and optional tags');
  await page.locator('#saved-destination').selectOption('new');await page.locator('#saved-project-name').fill('Saved workflow');
  // Both delivery attempts commit/replay but their responses are lost.
  const drops={};await page.route('**/api/v1/projects/saved-workflow/changes',async route=>{const phase=route.request().postDataJSON().operations[0].op;drops[phase]=drops[phase]||0;if(drops[phase]<2){drops[phase]++;await route.fetch();await route.abort();}else await route.continue();});
  await page.locator('#saved-publish').click();await page.locator('#saved-stage-recovery').getByRole('button',{name:'Retry original save'}).waitFor();assert.equal(await page.locator('#saved-controls').getAttribute('inert'),'');await page.goBack();await page.waitForFunction(()=>location.hash==='#view=library');assert.equal(await page.locator('#library-view').isVisible(),true);assert.equal(await page.locator('#saved-stage-recovery').getByRole('button',{name:'Retry original save'}).isVisible(),true);check('Unknown publication keeps its exact retry and prevents page departure');for(let phase=0;phase<3;phase++){await page.locator('#saved-stage-recovery').getByRole('button',{name:'Retry original save'}).click();if(phase<2)await page.locator('#saved-stage-recovery').getByRole('button',{name:'Retry original save'}).waitFor();}await page.locator('#saved-notice').filter({hasText:'Published 1 closed, protected project decisions.'}).waitFor();assert.deepEqual(Object.values(drops),[2,2,2]);await page.unroute('**/api/v1/projects/saved-workflow/changes');check('Lost create, close and protect responses replay the same requests without duplicates');
  const inspect=async()=>page.evaluate(async()=>{const ps=await (await fetch('/api/v1/projects')).json();const p=ps.data.find(x=>x.project_id==='saved-workflow');const r=await (await fetch('/api/v1/projects/saved-workflow/decisions',{headers:{'X-Ledger-UUID':p.ledger_uuid}})).json();return r;});
  assert.equal((await inspect()).data.length,1);assert.equal((await inspect()).data[0].status,'closed');assert.equal((await inspect()).data[0].locked,true);const approved=await page.evaluate(async()=>{const p=(await (await fetch('/api/v1/projects')).json()).data.find(x=>x.project_id==='saved-workflow');return (await (await fetch('/api/v1/projects/saved-workflow/decisions/D000001',{headers:{'X-Ledger-UUID':p.ledger_uuid}})).json()).data;});assert.equal(approved.latest_resolution_approval.mode,'authenticated_now');assert.equal(approved.planning_link.linked,false);assert.ok(approved.baseline.startsWith('publication-'));check('Publish records current operator approval and protection without another popup');
  await page.locator('#saved-group-filter').selectOption({label:'Websites'});await page.locator('#saved-manage-groups').click();await page.locator('#saved-group-list .saved-row').getByRole('button',{name:'Delete',exact:true}).click();await page.locator('#saved-group-list').getByText('No groups yet.').waitFor();await page.locator('#saved-group-close').click();assert.equal(await page.locator('#saved-group-filter option').count(),1);assert.equal(await page.locator('#saved-group-filter').inputValue(),'');assert.equal((await inspect()).data[0].title,'Reusable launch');
  await page.locator('#saved-list .saved-row').filter({hasText:'Reusable launch'}).locator('input').check();await page.locator('#saved-add').click();await page.locator('#saved-destination').selectOption('saved-workflow');await page.locator('#saved-publish').click();await page.locator('#saved-notice').filter({hasText:'Published 1 closed, protected project decisions.'}).waitFor();await page.waitForFunction(()=>document.querySelector('#saved-staging').textContent.includes('Staging is empty.'));
  assert.deepEqual((await inspect()).data.map(x=>x.key).sort(),['D000001','D000002']);check('Tags stop at staging; repeated publication uses the next decision number');
  await page.locator('#saved-list .saved-row').filter({hasText:'Refresh recovery'}).getByRole('button',{name:'View',exact:true}).click();let deleteDrops=0;await page.route('**/api/v1/saved-decisions/changes',async route=>{if(deleteDrops++<2){await route.fetch();await route.abort();}else await route.continue();});await page.locator('#saved-preview').getByRole('button',{name:'Delete',exact:true}).click();await page.locator('#saved-preview-recovery').getByRole('button',{name:'Retry original save'}).waitFor();assert.equal(await page.locator('#saved-preview-close').isDisabled(),true);await page.locator('#saved-preview-recovery').getByRole('button',{name:'Retry original save'}).click();await page.locator('#saved-preview').waitFor({state:'hidden'});await page.unroute('**/api/v1/saved-decisions/changes');assert.equal(await page.locator('#saved-list .saved-row').filter({hasText:'Refresh recovery'}).count(),0);assert.equal((await inspect()).data.length,2);check('Delete inside View retains its modal retry without changing injected records');
  await page.setViewportSize({width:390,height:844});await page.locator('#saved-panel-toggle').click();assert.equal(await page.locator('#saved-new').isVisible(),true);assert.equal(await page.locator('#library-staging').isVisible(),true);await page.locator('#saved-new').click();await page.locator('#saved-title').fill('Narrow draft');await page.screenshot({path:out+'/saved-narrow-form.png'});assert.ok(await page.locator('#saved-editor').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.locator('#saved-cancel').click();await page.locator('#saved-dirty-discard').click();await page.screenshot({path:out+'/saved-narrow.png'});assert.ok(await page.locator('#library-view').evaluate(e=>e.scrollWidth<=e.clientWidth+1));check('Narrow viewport exposes controls, staging and the familiar action form');
  if(process.env.PROOF_FULL_BROWSER){
   const extension=out+'/zoom-extension';fs.mkdirSync(extension,{recursive:true});fs.writeFileSync(extension+'/manifest.json',JSON.stringify({manifest_version:3,name:'Isolated saved-decision zoom verification',version:'1.0',permissions:['tabs'],background:{service_worker:'worker.js'}}));fs.writeFileSync(extension+'/worker.js','chrome.runtime.onInstalled.addListener(()=>{});');
   const context=await chromium.launchPersistentContext(out+'/zoom-profile',{headless:true,executablePath:process.env.PROOF_FULL_BROWSER,viewport:null,ignoreDefaultArgs:['--disable-extensions'],args:['--window-size=1440,1000',`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
   try{await context.addCookies(await page.context().cookies());const zoom=await context.newPage();await zoom.goto(origin);await zoom.locator('#projects-view').waitFor();const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');assert.equal(await worker.evaluate(async()=>{const tabs=await chrome.tabs.query({});const tab=tabs.find(t=>t.url.startsWith('http://127.0.0.1'));await chrome.tabs.setZoom(tab.id,2);return chrome.tabs.getZoom(tab.id);}),2);await zoom.locator('#saved-button').click();await zoom.locator('#saved-list').getByText('Reusable launch',{exact:true}).waitFor();await zoom.locator('#saved-panel-toggle').click();assert.equal(await zoom.locator('#saved-new').isVisible(),true);assert.equal(await zoom.locator('#library-staging').isVisible(),true);assert.ok(await zoom.locator('#library-view').evaluate(e=>{const r=e.getBoundingClientRect();return e.scrollWidth<=e.clientWidth+1&&r.left>=0&&r.right<=innerWidth+1;}));fs.writeFileSync(out+'/zoom-geometry.json',JSON.stringify(await zoom.evaluate(()=>({innerWidth,innerHeight,dpr:devicePixelRatio,dialog:document.querySelector('#library-view').getBoundingClientRect().toJSON()})),null,2));await zoom.bringToFront();await zoom.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const capture=await zoom.context().newCDPSession(zoom);const pixels=await capture.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});fs.writeFileSync(out+'/saved-200-percent.png',Buffer.from(pixels.data,'base64'));await capture.detach();check('Actual 200 percent browser zoom');}finally{await context.close();}
  }
  await page.setViewportSize({width:1440,height:1000});await page.locator('#saved-new').click();assert.equal(await page.locator('#saved-editor').evaluate(e=>e.open),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#saved-editor').isVisible(),false);assert.equal(await page.locator('#saved-new').evaluate(e=>e===document.activeElement),true);check('Keyboard action cancellation returns focus to Library controls');
  assert.deepEqual(errors,[]);fs.writeFileSync(out+'/checks.json',JSON.stringify({checks,errors},null,2));console.log(checks.join('\n'));
 }catch(e){await page.screenshot({path:out+'/failure.png',fullPage:true});fs.writeFileSync(out+'/failure.json',JSON.stringify({error:e.message,checks,errors,view:await page.evaluate(()=>({route:location.hash,notice:document.querySelector('#saved-notice')?.textContent,error:document.querySelector('#saved-error')?.textContent,stageError:document.querySelector('#saved-stage-recovery')?.textContent}))},null,2));throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
